micronaut:
  application:
    name: casadocodigo

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cdc
    driverClassName: org.postgresql.Driver
    username: keycloak
    password: password

jpa.default.properties.hibernate.hbm2ddl.auto: create-drop

